name: Secret Scan

on:
  push:
  pull_request:
  # schedule:
  #  - cron:  '0 0 * * *' # Runs every day at midnight or any time

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    name: Gitleaks
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: wget -O ./gitleaks.toml https://raw.githubusercontent.com/zricethezav/gitleaks/master/config/gitleaks.toml # download the default config
    - name: Gitleaks Action
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_NOTIFY_USER_LIST: "basingh" # Notify users in the list
        
    - name: Send GitHub Actions Report to Slack
      if: ${{ failure() }}
      id: slack
      uses: slackapi/slack-github-action@v1.25.0
      with: 
        channel-id: 'C5UP17XLG'
        payload: |
            {
                "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                "blocks": [
                 {
                    "type": "section",
                    "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    }
                 }
                ]
            }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


      # with:
      #  config-path: .gitleaks.toml # Optional: if you have a custom config
