name: Secret Scan

on:
  push:
  pull_request:
  # schedule:
  #  - cron:  '0 0 * * *' # Runs every day at midnight or any time

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    name: Gitleaks
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: wget -O ./gitleaks.toml https://raw.githubusercontent.com/zricethezav/gitleaks/master/config/gitleaks.toml # download the default config
    - name: Gitleaks Action
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_NOTIFY_USER_LIST: "basingh" # Notify users in the list
        
    - name: Send GitHub Actions Report to Slack
      if: ${{ failure() }}
      id: slack
      uses: act10ns/slack@v1
      with: |
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: ${{ secrets.SLACK_CHANNEL }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


      # with:
      #  config-path: .gitleaks.toml # Optional: if you have a custom config
